### ISSUE TITLE
What are BertExt, BertExtAbs, and BertSum? 

### ISSUE THREAD

**Issue by forrestbao** [Liyan06/AggreFact#10]
Hi, I am looking at the `model_name` column of the data you shared. What are the three models BertExt, BertExtAbs, and BertSum?  How are they related to BertSumExt and BertSumAbs of (Liu and Lapata, 2019)?

**Comment by Liyan06** [comment]
BertExt, BertExtAbs come from PolyTope: https://github.com/hddbang/PolyTope/tree/master/outputs_with_human_annotation
Those are indeed from Liu and Lapata, 2019. More details can be found in https://aclanthology.org/2020.emnlp-main.33.pdf.

**Comment by forrestbao** [comment]
Thanks. Then are there overlaps between BertExt/BertExtAbs and BertSum{Ext, Abs}? I do not wanna use the same or related samples twice.

**Comment by Liyan06** [comment]
We have ensured that there is no duplicated data in the benchmark.

**Comment by forrestbao** [comment]
I am sorry that I have taken you so much time. 
You explained that BertExt and bertExtAbs come from Polytope. 
Then what about BertSum? Where does it come from?

**Comment by Liyan06** [comment]
BertSum summaries are from FRANK.

**Comment by forrestbao** [comment]
Thanks for your reply.
