### ISSUE TITLE
What is PegasusDynamic in your data? 

### ISSUE THREAD

**Issue by forrestbao** [Liyan06/AggreFact#11]
Hi, I am looking at the data you provided. There is one summarizer model called `PegasusDynamic`. What is it? It is a variation of Pegasus?

**Comment by Liyan06** [comment]
We use this name directly from "SummEval: Re-evaluating Summarization Evaluation"

**Comment by forrestbao** [comment]
Thanks for your response. Are there overlaps between `Pegasus` and `PegasusDynamic` in your dataset? I do not wanna use the same sample twice when evaluating.

**Comment by Liyan06** [comment]
We have ensured that there is no duplicated data in the benchmark.
