### ISSUE TITLE
Summarizer `missing`

### ISSUE THREAD

**Issue by forrestbao** [Liyan06/AggreFact#12]
Hi, in your data, under the `model_name` column, some values are `missing`. Are samples of such a value in the `model_name` column counted into OLD, ExFormer, SOTA, or not used in your analysis at all"?

**Comment by Liyan06** [comment]
Hi, @forrestbao those should be counted into OLD. "missing" here means that the model names were not specified in original dataset construction. However, given the year those datasets were created, those "missing" models should be counted into OLD.
