### ISSUE TITLE
Release of AggreFact Unify dataset

### ISSUE THREAD

**Issue by cs329yangzhong** [Liyan06/AggreFact#13]
Will you be willing to release the AggreFact-unified dataset? Major findings in the paper stemmed from the error analysis and it is valuable as a benchmark dataset on hallucination detection.

thanks!

**Comment by Liyan06** [comment]
Hi, this is a good point! I'll take a look at my code and see if I can find the AggreFact-unified dataset. For now, if you are interested in error type detection, I recommend my latest work that focuses on LLMs' errors on dialogue summarization: 

TofuEval: Evaluating Hallucinations of LLMs on Topic-Focused Dialogue Summarization
https://arxiv.org/pdf/2402.13249.pdf

**Comment by cs329yangzhong** [comment]
Hi Liyan,

Any update on AggreFact-unified?

**Comment by Liyan06** [comment]
Hi, sorry for the delay. I'll release it shortly today.

**Comment by Liyan06** [comment]
I have updated the repo and you should be able to see AggraFact-Unifed now.
