### ISSUE TITLE
New paper version

### ISSUE THREAD

**Issue by UntotaufUrlaub** [Liyan06/AggreFact#5]
Hi,
I think it would be beneficial for people discovering your work if you added to the readme that there is a [new version of the paper available](https://arxiv.org/pdf/2205.12854v2.pdf) (as can be seen on this [overview](https://arxiv.org/abs/2205.12854v2)) and what the key differences are.

Probably it would also be nice to have access to the new csv file containing the chatgpt based metrics, so people could compare and verify your results etc.

kind regards

**Comment by Liyan06** [comment]
Thanks for the suggestion! We will update the repo shortly!
