### ISSUE TITLE
Sentence level dataset

### ISSUE THREAD

**Issue by ariecattan** [Liyan06/AggreFact#8]
Thanks for the great work, your benchmark is more than useful!  

Could you please provide the dataset at the sentence level? This is particularly helpful in CNN/DM summaries where some sentences might be faithful and others not.

**Comment by Liyan06** [comment]
Thanks for the question! We do not provide the dataset at the sentence level as for some datasets the human annotated label is on the summary level. We cannot easily obtain sentence-level annotation label based on summary-level labels.

**Comment by ariecattan** [comment]
Got it, thanks!
