### ISSUE TITLE
请问这些数据是怎么来的呢？

### ISSUE THREAD

**Issue by yaokunkun** [Liyan06/AggreFact#9]
我看代码好像是直接从csv表格现成的数据里提取的数据，只是做一些计算就得到了结果。我想问下大佬，某数据集在某方法（论文中的metric）下的分数，是怎么来的呢？比如对于一条BART模型摘要的CNN/DM数据样本，它在DAE得分是0.912，我了解的就是这个分数来源，是直接从以往的论文中得取的呢还是大佬用模型跑出来的呢？还望大佬赐教！

**Comment by Liyan06** [comment]
Hey, we obtain the scores by running these metrics on the data.
